const words = [
    'Asset Management',
    'Big Data',
    'Bitrix24',
    'BRM',
    'Cloud Computing',
    'Cloud Computing Architecture',
    'Database',
    'COBIT',
    'Cyber Security',
    'DaaS',
    'Data Center',
    'EMC2',
    'Field Services',
    'Fortinet',
    'Framework',
    'Hadoop',
    'IaaS',
    'IoT',
    'ISO',
    'ISMS',
    'ITAM',
    'KPI',
    'Hyper-V',
    'NetFlow',
    'QA',
    'Virtualización',
    'React',
    'ASP.NET MVC',
    'Angular',
    'Ruby on Rails',
    'AngularJS',
    'Vue.js',
    'Django',
    'Laravel',
    'ASP .NET',
    'Spring',
    'Express',
    'Flask',
    'Meteor',
    'Symfony',
    'CodeIgniter',
    'JSF',
    'Ember.js',
    '. NET Core',
    'Google Web Toolkit',
    'CakePHP',
    'Polymer',
    'Play',
    'Flex',
    'Sails.js',
    'Zend',
    'JHipster',
    'Tornado',
    'Yii',
    'Svelte',
    'Phoenix',
    'Sinatra',
    'Grails',
    'Aurelia',
    'Blade',
    'Koa',
    'Vert.x',
    'Slim',
    'FastAPI',
    'Phalcon',
    'Vapor',
    'LoopBack',
    'hapi',
    'Dropwizard',
    'AIOHTTP',
    'Feathers',
    'OpenUI5',
    'Oat ++',
    'Elm',
    'Bottle',
    'Wicket',
    'Dojo',
    'Pyramid',
    'Nancy',
    'Vaadin',
    'web.py',
    'Adonis',
    'Fastify',
    'Riot.js',
    'Struts',
    'Mithril',
    'web2py',
    'Lucky',
    'Revel',
    'Ktor',
    'Kohana',
    'Sanic',
    'Yesod',
    'Durandal',
    'Perfect',
    'Compojure',
    'CherryPy',
    'Mojolicious',
    'Ring',
    'Falcon',
    'Rocket',
    'Actix web',
    'SilverStripe Sapphire',
    'PHP',
    'Tapestry',
    'Martini',
    'Iris',
    'Marko',
    'FuelPHP',
    'Ninja',
    'Kitura',
    'Scalatra',
    'Restlet',
    'Sailor',
    'SproutCore',
    'Hanami',
    'Inferno',
    'Lift',
    'Lithium',
    'Buffalo',
    'Cappuccino',
    'ZK',
    'Flight',
    'servant',
    'Wt',
    'Grok',
    'Dancer2',
    'Ratpack',
    'Zope',
    'CompoundJS',
    'Catalyst',
    'Kemal',
    'TurboGears',
    'Gin',
    'Flatiron',
    'Noir',
    'Nitrogen',
    'Quart',
    'Amber',
    'Mojarra',
    'seaside',
    'Vanilla',
    'Stripes',
    'Masonite',
    'Camping',
    'Cuba',
    'kotlinx',
    'Happstack',
    'Zotonic',
    'Hyperstack',
    'Merb',
    'Cairngorm',
    'Rapidoid',
    'PureMVC',
    'Horde',
    'Ramaze',
    'Cocoon',
    'Spider',
    'Mate',
    'Orbit',
    'Tipfy',
    'Mason',
    'beego',
    'Swiz',
    'Prado',
    'Aura',
    'Picard',
    'Erlang',
    'JavaScriptMVC',
    'Solar',
    'Rum',
    'UKI',
    'Qcodo',
    'Cutelyst',
    'QCubed',
    'Apache',
    'Xitrum',
    'Swiftlet',
    'Hexagon',
    'Snap',
    'RestfulX',
    'Conjure',
    'Eliom',
    'Moustache',
    'KumbiaPHP',
    'MFlow',
    'echo',
    'Circumflex',
    'node',
    'Sin',
    'Portofino',
    'ErlyWeb',
    'Grain',
    'Nerve',
    'Lemmachine',
    'Wee',
    'Hemlock',
    'Konstrukt',
    'nodemachine',
    'simplex',
    'Nitro',
    'Halcyon',
    'Spincast',
    'Vroom',
    'Atomik',
    'Akelos',
    'mangoo',
    'Jifty',
    'Squatting',
    'Mack',
    'Webjure',
    'Waves',
    'Salvia',
    'LiquidLava',
    'CGI',
    'HydraMVC',
    'Roma',
    'NextJS',
    'JavaScript',
    'Python',
    'Java',
    'Go',
    'Python',
    'Java',
    'Go',
    'C ++',
    'Ruby',
    'PHP',
    'TypeScript',
    'C#',
    'C',
    'Shell',
    'Scala',
    'Swift',
    'Rust',
    'Kotlin',
    'Objetive -C',
    'Groovy',
    'Elixir',
    'Lua',
    'DM',
    'Perl',
    'Dart',
    'Clojure',
    'PowerShell',
    'CoffeeScript',
    'Haskell',
    'OCaml',
    'R',
    'Emacs Lisp',
    'Vim script',
    'Jsonnet',
    'Erlang',
    'Puppet',
    'Julia',
    'Smalltalk',
    'Matlab',
    'WebAssembly',
    'Fortran',
    'F #',
    'Visual  Basic',
    'Apex',
    'ABAP',
    'Vala',
    'Nix',
    'Crystal',
    'Roff',
    'Perl 6',
    'FreeMarker',
    'PureScript',
    'Objective -C++',
    "IT Svit",
    "Agent",
    "Agile software development",
    "Artifact",
    "Amazon AWS",
    "Ansible",
    "API",
    "Apache",
    "ALB",
    "ASG",
    "AWS CLI",
    "Application release automation",
    "Amazon Aurora",
    "the most rapidly growing service in AWS history",
    "Asterisk",
    "Bastion host",
    "Branching",
    "Bucket",
    "Backup",
    "Back-end",
    "Build",
    "Bare-metal",
    "Canary release",
    "Cloud computing",
    "Continuous Delivery",
    "Continuous Deployment",
    "CI/CD",
    "Cluster",
    "bare-metal servers",
    "Commit",
    "Cron job",
    "Container",
    "CloudWatch",
    "Configuration drift",
    "Configuration management",
    "DevOps",
    "Dark launch",
    "Docker",
    "Dockerfile",
    "Docker Swarm",
    "Deployment",
    "Django framework",
    "Datadog",
    "Environment",
    "ElasticSearch",
    "Envoy",
    "EC2",
    "EKS",
    "FluentD",
    "Fargate",
    "Fail-fast",
    "Git",
    "GitHub",
    "GitLab",
    "Gitlab CI",
    "Helm",
    "Infrastructure",
    "IaC",
    "Kubernetes or Terraform",
    "IaaS",
    "Image",
    "InfluxDB",
    "DevOps tools",
    "Instance",
    "I/O throughput",
    "Ingress controller",
    "Jenkins",
    "Jenkins job",
    "Kubernetes",
    "Kubernetes and Docker",
    "Kibana",
    "Logstash",
    "Lead time",
    "Microservices",
    "MongoDB",
    "MTTR",
    "Node",
    "Node pool",
    "Nexus3",
    "Nginx",
    "Orchestration",
    "Terraform",
    "Open source",
    "OpenStack",
    "OpenShift",
    "PaaS",
    "Prometheus",
    "Provisioning",
    "Terraform and Kubernetes",
    "Python",
    "Pod",
    "ProxMox",
    "Production environment",
    "RDS",
    "Rolling update",
    "Rollback",
    "Regression testing",
    "RabbitMQ",
    "Source control",
    "S3",
    "Snapshot",
    "Staging environment",
    "Test automation",
    "Technical debt",
    "Unit testing",
    "Virtual machine",
    "VPC peering",
    "AWS VPC peering",
    "Vault",
    "Zabbix"
]
//hasta aqui puras palabras del mundo de programacion y arquitectura, falta css marketing,  y quizas secciones de platzi. como escuelas, despues cosas de medicina,cosas fitner y seria'.
export {words};